name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ConsoleApp1

    - name: Build
      run: dotnet build --configuration Release
      working-directory: ConsoleApp1
